# Generated by Django 3.2.4 on 2021-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
